apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-sa
  namespace: kubernetes-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-role
subjects:
- kind: ServiceAccount
  name: monitor-sa
  namespace: kubernetes-monitoring

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-monitory
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-monitory-nfs
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitory-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  mountOptions:
  - nfsvers=3
  - nolock
  nfs:
    path: /nfs/monitory # NFS folder to python script
    server: <nfs_server_IP>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-monitory
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitory-nfs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  mountOptions:
  - nfsvers=3
  - nolock
  nfs:
    path: /nfs/ # Root NFS folder
    server: <nfs_server_IP>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-monitory-nfs
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitory-pvc
  namespace: kubernetes-monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-monitory
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitory-nfs-pvc
  namespace: kubernetes-monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-monitory-nfs
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitory-deployment
  namespace: kubernetes-monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: monitory
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitory
    spec:
      containers:
      - args:
        - |
          apk add --no-cache python3 py3-pip py3-reportlab
          python /tmp/main.py
          while true; do
            echo "Ejecutandose ...."  
            sleep 3600;
          done
        command:
        - /bin/sh
        - -c
        image: alpine/kubectl:1.34.2
        imagePullPolicy: IfNotPresent
        name: kubectl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/
          name: monitory-data
        - mountPath: /mnt/nfs-server
          name: nfs-server
        - mountPath: /etc/localtime
          name: tz-config
          readOnly: true
        - mountPath: /etc/timezone
          name: tz-config2
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: monitor-sa
      serviceAccountName: monitor-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: monitory-data
        persistentVolumeClaim:
          claimName: monitory-pvc
      - name: nfs-server
        persistentVolumeClaim:
          claimName: monitory-nfs-pvc
      - hostPath:
          path: /etc/localtime
          type: ""
        name: tz-config
      - hostPath:
          path: /etc/timezone
          type: ""
        name: tz-config2
